# Generated by Django 5.2.1 on 2025-07-29 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crud',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
